### ISSUE TITLE
Report error when extension window is closed

### ISSUE THREAD

**Issue by Necroskillz** [airgap-it/beacon-extension#15] opened 2020-08-26 13:59 UTC
If the user closes the extension popup window (e.g. after a permission request or operation request), dapp has no way to tell that it happened (so UI can show error/unblock UI, stop waiting and allow the user to try again).

Relevant promise should be rejected. This would be consistent with how Thanos handles it.

**Comment by AndreasGassmann** [comment] 2020-08-31 12:46
Hi, thanks for opening the issue.

We will try to improve this behaviour, but the problem is that we don't only allow connections to browser extensions, but also over the P2P network. In the latter case, things are a little more inconsistent. For example, we can't know if the wallet has received/handled our request. So even if we send back an error by default, you couldn't rely on it in the DApp. So the case where there is simply no response has to be handled either way.

**Comment by AndreasGassmann** [comment] 2021-02-04 15:33
This will be included in the next release. However, the "abort" message cannot be expected in every case, because P2P wallets might not send an abort message (eg. when the app is sent to the background).

**Closed as completed by AndreasGassmann** 2021-02-04 15:33 UTC
